Clean up plotline (spaces to tab)

diff --git a/home/joxit/bin/plotline b/home/joxit/bin/plotline
--- a/home/joxit/bin/plotline
+++ b/home/joxit/bin/plotline
@@ -46,23 +46,23 @@ function usage {
 }
 
 function checkrange {
-    res=`echo "$1" | egrep -ci "\[-?([0-9]*|\*|([0-9]+\*)*pi(\*[0-9]+)*):-?([0-9]*|\*|([0-9]+\*)*pi(\*[0-9]+)*)\]"` 
-    if [ $res == 0 ]
-    then
+	res=`echo "$1" | egrep -ci "\[-?([0-9]*|\*|([0-9]+\*)*pi(\*[0-9]+)*):-?([0-9]*|\*|([0-9]+\*)*pi(\*[0-9]+)*)\]"`
+	if [ $res == 0 ]
+	then
 		echo "Warning range $1!" 1>&2
 		echo "Syntax:" 1>&2
 		echo "[{<dummy-var>=}{{<min>}:{<max>}}]" 1>&2
 		echo "[{{<min>}:{<max>}}]" 1>&2
-    fi
+	fi
 }
 
 if [ $# == 0 ]
 then
-    usage
+	usage
 fi 
 
 while [ "$1" != "" ]; do
-    case "$1" in
+	case "$1" in
 		-t|--title) 
 			shift
 			TITLE="set title '$1'"
@@ -117,14 +117,14 @@ while [ "$1" != "" ]; do
 			echo "$0 : Invalid option"
 			usage
 			;;
-    esac
-    shift
+	esac
+	shift
 done
 if [ $n == 1 ] 
 then
-    echo "Error: No input" 1>&2
-    usage
-    exit -1
+	echo "Error: No input" 1>&2
+	usage
+	exit -1
 fi
 echo $PLOT 1>&2
 gnuplot << EOF
